name: DevotedPvP
authors: [Maxopoly, TeaJizzle, TealNerd, ProgrammerDan, KaloHG, Amel, oko]
version: ${project.version}
main: com.biggestnerd.devotedpvp.DevotedPvP
depend: [CivModCore]
softdepend: [Vault]
api-version: 1.13
commands:
  inv:
    description: "Save/load inventories."
    usage: "Usage: /inv save/load <inventory> or /inv clear."
    permission: pvp.use
  duel:
    description: Requests to duel someone
    usage: /duel <playername>
    permission: pvp.duel
  accept:
    description: Accept the last duel request
    usage: /accept
    permission: pvp.duel
  clear:
    usage: /clear
    permission: pvp.duel
  forfeit:
    description: Forfeit a duel
    usage: /forfeit
    permisson: pvp.use
    aliases: [ff, surrender]
  elo:
    description: Check your elo
    usage: /elo
    permission: pvp.duel
    aliases: [rank]
  wm:
    permission: pvp.badmin
    aliases: [warpmanage]
  spectate:
    permission: pvp.use.spectate
permissions:
  pvp.use:
    description: "use inventory saving/loading."
    default: true
  pvp.use.spectate:
    description: "use spectate command"
    default: true
  pvp.duel:
    description: "allows players to duel"
    default: true 
  pvp.badmin:
    description: "Admin crimes inc"
    default: op
